services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: db
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://admin:P@ssw0rd@postgres:5432/db?schema=public
    ports:
      - '3000:3000'

volumes:
  postgres_data:
